### PR TITLE
Add updater tests

### LINKED ISSUE #16: tests: Add unit tests for Updater

### PR DESCRIPTION
**Pull request by ivanayov**
This change provides few bug fixes in the metadata and the updater, 
implements repository simulator and updater tests

Resolves #16

### CODE REVIEW

**Comment by rdimitrov** [comment]
@ivanayov Hey, it seems you haven't incorporated the latest logging changes from @MDr164. 

I've tried doing that for you, but when I did I encounter an error while running the tests. Can you have a look?

I'm sharing the branch with what I did so far trying to add the logging changes on top of your PR so it can save some time for you hopefully - https://github.com/rdimitrov/go-tuf-metadata/tree/ivana-tests. 

Feel free to use it as a base, but do check if I haven't messed up something while putting these changes on top.

**Comment by MDr164** [comment]
I can also have a look later, got a bit of time at my disposal so I'll check if I can run the new tests here and if not fix those accordingly.

**Comment by MDr164** [comment]
Ok it seems like the helper function `initUpdater` in `updater_top_level_update_test.go` return a nil pointer and that causes the test suite to crash. I'll fix  that as soon as I get around working on it today. I'll take a bit of time to go through this giant new test collection.

**Comment by MDr164** [comment]
I added another draft at #67 but I feel like the issue lays quite deep in the code as we are missing some nil checks and the currents tests are really fragile (they don't run on my machine at all due to how the new simulator is constructed but they run in CI). I'll try to hot fix the PR so it passes in the CI and afterwards take the general flow of possible tests cases and make it more generic I suppose.

**Comment by ivanayov** [comment]
Hi @MDr164, what failure do you get on your machine?

**Comment by MDr164** [comment]
```console
updater_consistent_snapshot_test.go:59: failed to create new updater config, reason rename /home/user/private/cncf/go-tuf-metadata/metadata/updater/tuf_tmp493854732 /tmp/07502509058968/metadata/root.json: invalid cross-device link
```

The simulator (and all other existing helper functions as of right now) don't utilize `t.TempDir()` which would guarantee a threadsafe bringup and teardown of the testing environment but rather use `*testing.M` for bringup and teardown which is considered an antipattern in Go. Though the updater tests are not the only ones having issues. On my machine the tmpdirs are isolated thus I can't do cross device links into my home partition which the tests are touching.

**Comment by ivanayov** [comment]
Pushed a fix, sorry for the short delay.
There was a change in the updater's DownloadFile method layout, which is implemented by RepositorySimulator and so the change breaks the whole implementation. I fixed that and the logrus dependency issue.

Will follow-up with a fix for the linter.

**Comment by MDr164** [comment]
There was also a change regarding logging (it's now optional and uses a slightly different API) that you'd have to pull into your PR, as noted earlier in the discussion you can probably just pick the commit from Radoslav.

**Comment by ivanayov** [comment]
I pulled from latest main, so they are now present here. 

Ah, I see for the tmp dir. Thanks for catching that! Should I provide a fix or you already worked on that?

**Comment by MDr164** [comment]
I discussed with Radoslav that your PR should just go in as is for a bump in coverage (once CI is happy) and I'll push my followup afterwards, so don't worry reworking your tests for now.

**Comment by ivanayov** [comment]
All fixed, but I give up on that negative test increase 😄 The tests provide 64.8% coverage of the updater (compared to 0% without). I need to check what causes that miscalculation.

**Comment by MDr164** [comment]
Oh I know the reason, the CI did not have the `-coverpkg` flag set, so that means only packages that had a test file will be included into coverage. The updater did not have one so it was previously excluded from coverage reports. Now that you added one it got added into the report but because you did not reach 100% it detected a decline. I will quickly create a PR so that we get the real coverage number.

**Review by MDr164 — APPROVED** [review]
lgtm, CI passes and lots of code gets covered

**Comment by ivanayov** [comment]
Thanks @MDr164 :)

**Review by rdimitrov — APPROVED** [review]
@ivanayov - Thanks again for your contribution! 🎉

**Comment by rdimitrov** [comment]
@MDr164 - Thank you for reviewing and helping sorting this out! 😃💯

**Pull request merged**
