### PR TITLE
Added an unsafe method for loading the tuf metadata on disk

### PR DESCRIPTION
**Pull request by kommendorkapten**

### CODE REVIEW

**Comment by rdimitrov** [comment]
@kommendorkapten - Thanks for this 💯 

What would you think about:
* Creating a setting in the updater configuration that we can toggle for allowing to work in this unsafe mode
* Make this a private method to updater
* Extract the current content of the Refresh into another private method
* Upon calling Refresh, we'll decide which method to call based on the setting (default being the safe one)?

Other:
* What is the best way to incorporate that setting with enabling Refresh to be called multiple times without failing? Perhaps we can have separate settings for each (one to work in offline mode, the other to allow for multiple calls of Refresh?) or something else?

**Comment by kommendorkapten** [comment]
@rdimitrov updated to use a parameter instead. Note that calling `Refresh` multiple times will still fail, I can work around that so it's not important I believe.

**Comment by kommendorkapten** [comment]
If you think this is good, I'll start to work on getting the tests updated.

**Comment by kommendorkapten** [comment]
> While doing the tests can you verify if this option works together with DisableLocalCache and if they affect each other, add a check that we cannot set both at the same time?

Is this really needed?
* `DisableLocalCache` makes sure nothing is persisted to the filesystem.
* `UnsafeLocalMode` makes sure nothing is fetched from the network.

I think it makes sense to allow them together, as even with `UnsafeLocalMode`, the provided root.json is actually written to disk.

**Comment by rdimitrov** [comment]
> > While doing the tests can you verify if this option works together with DisableLocalCache and if they affect each other, add a check that we cannot set both at the same time?
> 
> Is this really needed?
> 
> * `DisableLocalCache` makes sure nothing is persisted to the filesystem.
> * `UnsafeLocalMode` makes sure nothing is fetched from the network.
> 
> I think it makes sense to allow them together, as even with `UnsafeLocalMode`, the provided root.json is actually written to disk.

Actually I did not put a lot of thought on it while I asked that, just thought to bring that up to you so if someone enables both it doesn't accidentally interfere with the behaviour of this patch 👍

**Review by rdimitrov — APPROVED** [review]

**Pull request merged**
